package com.beyourself.schemaregistry.controller;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.ClassPathResource;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Serves Kafka event schema metadata from the SSOT manifest.json
 * (generated by common-module's EventContractSchemaWriter).
 *
 * <p>All endpoints are read-only. No database required.
 *
 * <p>Topic deduplication: the manifest lists every version as a separate
 * entry (e.g. {@code workflow.expense.incurred.v1}, {@code ...v2}).
 * The {@code /topics} endpoint deduplicates by stripping the {@code .vN}
 * suffix and returns only the latest version per topic group, so the
 * frontend dropdown shows one row per logical topic.
 *
 * @since 2026-06-02
 */
@RestController
@RequestMapping("")
public class SchemaRegistryController {

    private static final Logger log = LoggerFactory.getLogger(SchemaRegistryController.class);
    private static final String MANIFEST_PATH = "kafka-event-schemas/manifest.json";
    private static final String SCHEMAS_DIR = "kafka-event-schemas/schemas/";
    private static final Pattern BASE_TOPIC_PATTERN = Pattern.compile("^(.+)\\.v(\\d+)$");

    private final ObjectMapper objectMapper;

    public SchemaRegistryController(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    /**
     * List deduplicated topics — only the latest version of each logical
     * topic, with domain and human-readable label.
     */
    @GetMapping("/topics")
    public ResponseEntity<List<Map<String, String>>> listTopics() {
        try {
            Map<String, Object> manifest = loadManifest();
            @SuppressWarnings("unchecked")
            List<Map<String, Object>> entries = (List<Map<String, Object>>) manifest.get("entries");

            Map<String, Map<String, String>> latestByBase = new LinkedHashMap<>();

            if (entries != null) {
                for (Map<String, Object> entry : entries) {
                    String topic = String.valueOf(entry.get("topic"));
                    String domain = String.valueOf(entry.getOrDefault("domain", ""));
                    int version = ((Number) entry.getOrDefault("version", 1)).intValue();

                    // Extract base topic (strip .vN suffix)
                    ParsedTopic parsed = parseTopic(topic);

                    Map<String, String> existing = latestByBase.get(parsed.base);
                    if (existing == null || parsed.version > version) {
                        Map<String, String> item = new LinkedHashMap<>();
                        item.put("topic", topic);
                        item.put("baseTopic", parsed.base);
                        item.put("version", String.valueOf(version));
                        item.put("domain", domain);
                        item.put("label", topic);
                        latestByBase.put(parsed.base, item);
                    }
                }
            }

            return ResponseEntity.ok(new ArrayList<>(latestByBase.values()));
        } catch (Exception e) {
            log.error("Failed to list topics", e);
            return ResponseEntity.internalServerError().build();
        }
    }

    /**
     * Get the JSON Schema for a topic. Accepts both the full topic name
     * (e.g. {@code workflow.expense.incurred.v2}) and the base name
     * (e.g. {@code workflow.expense.incurred}), which returns the latest
     * version's schema.
     */
    @GetMapping(value = "/schemas/{topic}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<String> getSchema(@PathVariable String topic) {
        try {
            Map<String, Object> manifest = loadManifest();
            @SuppressWarnings("unchecked")
            List<Map<String, Object>> entries = (List<Map<String, Object>>) manifest.get("entries");

            if (entries == null) {
                return ResponseEntity.notFound().build();
            }

            // Try exact match first, then latest-by-base
            String schemaPath = findByTopic(entries, topic);
            if (schemaPath == null) {
                ParsedTopic parsed = parseTopic(topic);
                if (parsed.version == -1) {
                    // User passed a base name — find latest version
                    schemaPath = findLatestByBase(entries, parsed.base);
                }
            }

            if (schemaPath == null) {
                return ResponseEntity.notFound().build();
            }

            return serveSchemaFile(schemaPath);
        } catch (Exception e) {
            log.error("Failed to get schema for topic={}", topic, e);
            return ResponseEntity.internalServerError().build();
        }
    }

    /**
     * Return the full manifest.json.
     */
    @GetMapping(value = "/manifest", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<String> getManifest() {
        try {
            ClassPathResource resource = new ClassPathResource(MANIFEST_PATH);
            if (!resource.exists()) {
                return ResponseEntity.notFound().build();
            }
            try (InputStream in = resource.getInputStream()) {
                return ResponseEntity.ok(new String(in.readAllBytes(), StandardCharsets.UTF_8));
            }
        } catch (Exception e) {
            log.error("Failed to read manifest", e);
            return ResponseEntity.internalServerError().build();
        }
    }

    // ── private helpers ─────────────────────────────────────────

    private Map<String, Object> loadManifest() throws Exception {
        ClassPathResource resource = new ClassPathResource(MANIFEST_PATH);
        try (InputStream in = resource.getInputStream()) {
            String json = new String(in.readAllBytes(), StandardCharsets.UTF_8);
            return objectMapper.readValue(json, new TypeReference<>() {});
        }
    }

    private ParsedTopic parseTopic(String topic) {
        Matcher m = BASE_TOPIC_PATTERN.matcher(topic);
        if (m.matches()) {
            return new ParsedTopic(m.group(1), Integer.parseInt(m.group(2)));
        }
        return new ParsedTopic(topic, -1);
    }

    private String findByTopic(List<Map<String, Object>> entries, String topic) {
        for (Map<String, Object> entry : entries) {
            if (topic.equals(String.valueOf(entry.get("topic")))) {
                return String.valueOf(entry.get("schemaPath"));
            }
        }
        return null;
    }

    private String findLatestByBase(List<Map<String, Object>> entries, String baseTopic) {
        String bestPath = null;
        int bestVersion = -1;
        for (Map<String, Object> entry : entries) {
            String topic = String.valueOf(entry.get("topic"));
            ParsedTopic parsed = parseTopic(topic);
            if (parsed.base.equals(baseTopic) && parsed.version > bestVersion) {
                bestVersion = parsed.version;
                bestPath = String.valueOf(entry.get("schemaPath"));
            }
        }
        return bestPath;
    }

    private ResponseEntity<String> serveSchemaFile(String schemaPath) throws Exception {
        String filename = schemaPath.replace("schemas/", "");
        ClassPathResource resource = new ClassPathResource(SCHEMAS_DIR + filename);
        if (!resource.exists()) {
            return ResponseEntity.notFound().build();
        }
        try (InputStream in = resource.getInputStream()) {
            return ResponseEntity.ok(new String(in.readAllBytes(), StandardCharsets.UTF_8));
        }
    }

    private record ParsedTopic(String base, int version) {}
}
