package com.beyourself.schemaregistry.controller;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.ClassPathResource;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Serves Kafka event schema metadata from the SSOT manifest.json
 * (generated by common-module's EventContractSchemaWriter).
 *
 * <p>All endpoints are read-only. No database required.
 *
 * @since 2026-06-02
 */
@RestController
@RequestMapping("")
public class SchemaRegistryController {

    private static final Logger log = LoggerFactory.getLogger(SchemaRegistryController.class);
    private static final String MANIFEST_PATH = "kafka-event-schemas/manifest.json";
    private static final String SCHEMAS_DIR = "kafka-event-schemas/schemas/";

    private final ObjectMapper objectMapper;

    public SchemaRegistryController(ObjectMapper objectMapper) {
        this.objectMapper = objectMapper;
    }

    /**
     * List all Kafka topics with domain metadata.
     */
    @GetMapping("/topics")
    public ResponseEntity<List<Map<String, String>>> listTopics() {
        try {
            Map<String, Object> manifest = loadManifest();
            @SuppressWarnings("unchecked")
            List<Map<String, Object>> entries = (List<Map<String, Object>>) manifest.get("entries");

            List<Map<String, String>> topics = new ArrayList<>();
            if (entries != null) {
                for (Map<String, Object> entry : entries) {
                    Map<String, String> item = new LinkedHashMap<>();
                    item.put("topic", String.valueOf(entry.get("topic")));
                    item.put("domain", String.valueOf(entry.getOrDefault("domain", "")));
                    item.put("label", String.valueOf(entry.get("topic")));
                    topics.add(item);
                }
            }
            return ResponseEntity.ok(topics);
        } catch (Exception e) {
            log.error("Failed to list topics", e);
            return ResponseEntity.internalServerError().build();
        }
    }

    /**
     * Get the JSON Schema for a specific topic.
     */
    @GetMapping(value = "/schemas/{topic}", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<String> getSchema(@PathVariable String topic) {
        try {
            Map<String, Object> manifest = loadManifest();
            @SuppressWarnings("unchecked")
            List<Map<String, Object>> entries = (List<Map<String, Object>>) manifest.get("entries");

            if (entries == null) {
                return ResponseEntity.notFound().build();
            }

            String schemaPath = null;
            for (Map<String, Object> entry : entries) {
                if (topic.equals(String.valueOf(entry.get("topic")))) {
                    schemaPath = String.valueOf(entry.get("schemaPath"));
                    break;
                }
            }

            if (schemaPath == null) {
                return ResponseEntity.notFound().build();
            }

            ClassPathResource resource = new ClassPathResource(SCHEMAS_DIR + schemaPath.replace("schemas/", ""));
            if (!resource.exists()) {
                return ResponseEntity.notFound().build();
            }

            try (InputStream in = resource.getInputStream()) {
                return ResponseEntity.ok(new String(in.readAllBytes(), StandardCharsets.UTF_8));
            }
        } catch (Exception e) {
            log.error("Failed to get schema for topic={}", topic, e);
            return ResponseEntity.internalServerError().build();
        }
    }

    /**
     * Return the full manifest.json.
     */
    @GetMapping(value = "/manifest", produces = MediaType.APPLICATION_JSON_VALUE)
    public ResponseEntity<String> getManifest() {
        try {
            ClassPathResource resource = new ClassPathResource(MANIFEST_PATH);
            if (!resource.exists()) {
                return ResponseEntity.notFound().build();
            }
            try (InputStream in = resource.getInputStream()) {
                return ResponseEntity.ok(new String(in.readAllBytes(), StandardCharsets.UTF_8));
            }
        } catch (Exception e) {
            log.error("Failed to read manifest", e);
            return ResponseEntity.internalServerError().build();
        }
    }

    private Map<String, Object> loadManifest() throws Exception {
        ClassPathResource resource = new ClassPathResource(MANIFEST_PATH);
        try (InputStream in = resource.getInputStream()) {
            String json = new String(in.readAllBytes(), StandardCharsets.UTF_8);
            return objectMapper.readValue(json, new TypeReference<>() {});
        }
    }
}
